
package myfarm.Escenario;

/**
 *
 * @author annelis
 */
public class Ventana extends javax.swing.JFrame {

    Casilla[][] botones = new Casilla[5][5]; 
    private int filas = 5;
    private int columnas = 5;
    
    
   
    public Ventana() {
        this.botones = new Casilla[filas][columnas];
        initComponents();
        creacionCasilla();
        
        // Es para que aparezca en el centro y no apareza
        // en la derecha o izquierda
        this.setLocationRelativeTo(null);
    }

    public Ventana(String myFarm) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelNickName = new javax.swing.JLabel();
        jTextFieldLlenarNombre = new javax.swing.JTextField();
        jTextFieldLlenarNickName = new javax.swing.JTextField();
        jButtonIniciarJuego = new javax.swing.JButton();
        jPanelEscenario = new javax.swing.JPanel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setBackground(new java.awt.Color(204, 0, 51));
        jLabelNombre.setFont(new java.awt.Font("aakar", 3, 24)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabelNickName.setBackground(new java.awt.Color(255, 0, 51));
        jLabelNickName.setFont(new java.awt.Font("aakar", 3, 24)); // NOI18N
        jLabelNickName.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNickName.setText("Nickname:");
        getContentPane().add(jLabelNickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jTextFieldLlenarNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldLlenarNombre.setFont(new java.awt.Font("aakar", 3, 18)); // NOI18N
        jTextFieldLlenarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLlenarNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLlenarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 170, -1));

        jTextFieldLlenarNickName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldLlenarNickName.setFont(new java.awt.Font("aakar", 3, 18)); // NOI18N
        getContentPane().add(jTextFieldLlenarNickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 180, -1));

        jButtonIniciarJuego.setBackground(new java.awt.Color(255, 255, 0));
        jButtonIniciarJuego.setFont(new java.awt.Font("aakar", 3, 24)); // NOI18N
        jButtonIniciarJuego.setForeground(new java.awt.Color(255, 255, 51));
        jButtonIniciarJuego.setText("Jugar");
        getContentPane().add(jButtonIniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jPanelEscenario.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelEscenarioLayout = new javax.swing.GroupLayout(jPanelEscenario);
        jPanelEscenario.setLayout(jPanelEscenarioLayout);
        jPanelEscenarioLayout.setHorizontalGroup(
            jPanelEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanelEscenarioLayout.setVerticalGroup(
            jPanelEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelEscenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 600, 440));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_principal.jpeg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLlenarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLlenarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLlenarNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Ventana().setVisible(true);
                
            }
            
        });
    }
    
    
 /*
 * Se creara un arreglo bidimensional para crear el terreno
 * donde iran los animales y plantas, para esto se utilizará botones
 */
    public void creacionCasilla(){
        for (int fila = 0; fila<filas;fila++){
                    for (int columna = 0; columna<columnas;columna++){
                        botones[fila][columna] = new Casilla(45*columna, 30*fila,55,45);
                        botones[fila][columna].setTerrenosCasilla(fila,columna);
                        jPanelEscenario.add( botones [fila][columna] );
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciarJuego;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNickName;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanelEscenario;
    private javax.swing.JTextField jTextFieldLlenarNickName;
    private javax.swing.JTextField jTextFieldLlenarNombre;
    // End of variables declaration//GEN-END:variables
}
